i18n国際化
nobuyotanaka/fjord-books_app pull request #1
Opened 2022-06-26 10:01 UTC by nobuyotanaka

2022-06-30 09:53 UTC, u1tnk requested changes

2022-06-30 09:53 UTC, u1tnk commented on app/views/books/index.html.erb
> +      <th><%=t ('activerecord.attributes.book.title')%></th>
プラクティスに

> [Rails 国際化 (i18n) API - Railsガイド](https://railsguides.jp/i18n.html) を読み、使えそうなメソッドがあれば積極的に使う

とあるので、ここで使えそうなメソッドを探してみましょう 💪

2022-07-01 12:29 UTC, nobuyotanaka commented
再度修正しましたので、ご確認よろしくお願いします！

2022-07-01 12:44 UTC, nobuyotanaka commented on app/views/books/index.html.erb
> +      <th><%=t ('activerecord.attributes.book.title')%></th>
ヒントありがとうございます！
ごちゃごちゃとした書き方が気になっていたので、アドバイス助かります！

2022-07-10 09:29 UTC, u1tnk approved these changes

2022-07-21 12:17 UTC, merged